version: '3.10.12'

services:
  apppredictiondsfinal:
    container_name: apppredictiondsfinal
    image: matthewdulcich/apppredictiondsfinal
    ports:
      - "5001:5001"
    build:
      context: .
      dockerfile: Dockerfile